# Row vector

In [16]:
import numpy as np 
vec = [3, 4]
def rv(value_list):
    return np.array([value_list]) # It is important to add braket here, otherwise the transpose doesn't work
print(rv(vec))

[[3 4]]


# Column vector 

In [17]:
import numpy as np
def cv(value_list):
    return rv(value_list).T

print(cv(vec))

[[3]
 [4]]


# Length

In [18]:
import numpy as np 
def length(col_v):
    
    return np.sqrt(np.sum(col_v*col_v))

print(length(cv(vec)))

5.0


# Normalize a column vector

In [19]:
import numpy as np 
def normalize(col_v):
    return col_v / length(col_v)

normalize(cv(vec))

array([[0.6],
       [0.8]])

# Indexing

In [38]:
import numpy as np 
vec2D = np.array([[1, 2, 3], [4, 5, 5], [6, 7, 8]])
print(vec2D)
print(vec2D.ndim)
print(np.array([vec2D[:, -1]]).T)
print(vec2D[:, -1:])
# return the last col as 2D array
def index_final_col(A):
    return A[:, -1:]
index_final_col(vec2D)

[[1 2 3]
 [4 5 5]
 [6 7 8]]
2
[[3]
 [5]
 [8]]
[[3]
 [5]
 [8]]


array([[3],
       [5],
       [8]])

# Representing data 

## Alice has collected weight and height data of 3 people and has written it down below: 
## Weight, height
## 150, 5.8
## 130, 5.5
## 120, 5.3

## She wants to put this into a numpy array such that each row represents one individual's height and weight in the order listed. Write code to set data equal to the appropriate numpy array:

### Tnat de ligne que d'observation(personne ici) et tand de colonne que de feature(weight et height ici)

In [40]:
import numpy as np
data = np.array([[150, 5.8], [130, 5.5], [120, 5.3]])
print(data)

[[150.    5.8]
 [130.    5.5]
 [120.    5.3]]


# Matrix multiplication
## Now she wants to compute the sum of each person's height and weight as a column vector by multiplying data by another numpy array. She has written the following incorrect code to do so and needs your help to fix it:



In [45]:
import numpy as np
def transform(data):
    return (np.dot(data, np.array([[1], [1]])))

print(transform(data))

[[155.8]
 [135.5]
 [125.3]]
