# Slicing in python

In [2]:
import numpy as np

In [3]:
x = 'universe'
print(x[2:4])

iv


In [4]:
print(x[0:])
print(x[:-1])

universe
univers


In [5]:
print(x[2::3])
x[::]==x[0:len(x):1]

ir


True

In [6]:
print(x[::-1])

esrevinu


In [7]:
l = [1, 2, 3, 4]
print(l[2:])

[3, 4]


In [8]:
print(l[3:])

[4]


In [9]:
print(l[::])

[1, 2, 3, 4]


In [10]:
print(l[:-1:2])

[1, 3]


# Numpy slicing 

In [11]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
print(a[2:6:2])

[2 4]


In [13]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [14]:
print(a[1:-1])

[1 2 3 4 5 6 7 8]


In [15]:

print(a[:1:-2])

[9 7 5 3]


In [16]:
print(a[-1:1:-2])

[9 7 5 3]


## The two previous examples are the same. Why? Beacause for negative step the defaut start index is -1

In [17]:
l = list(range(10))
l[::2] = 99

TypeError: must assign iterable to extended slice

In [ ]:
a = np.arange(10)
a[::2] = 99
print(a)

[99  1 99  3 99  5 99  7 99  9]


# Multi-dimensional slicing

In [ ]:
a = np.arange(16)
a = a.reshape((4,4))
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# print second column
print(a[:,1])

[ 1  5  9 13]


In [ ]:
# print second row
print(a[1,:])

[4 5 6 7]


In [ ]:
# second row and every element at evenly index
print(a[1,::-2])

[7 5]


In [ ]:
# All column expect last one
print(a)
print(a[:, :-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [ ]:
# All row expect last one
print(a)
print(a[:-1, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# All column expect first one
print(a)
print(a[:, 1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
# All row expect first one
print(a)
print(a[1:, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
# all row expect the last one 
print(a)
print(a[:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a = np.arange(27)
a = a.reshape((3, 3, 3))
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(a[0,...,0])
# select first element of axis zero and first element of axis 2. Keep the rest.


[0 3 6]


In [ ]:
print(a[0,:, 0])

[0 3 6]


In [ ]:
a = np.arange(3*3)
a = a.reshape((3,3))

b = np.array(
    [[False, False, True],
    [False, True, False],
    [True, False, False]])
    

In [ ]:
print(a)
print(a[b])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 4 6]


In [ ]:
print('\"hello' + " " + "word's end\"")

"hello word's end"


In [ ]:
def ifConfusion(x, y):
    if x+y>0:
        while y>x:
            y = y -1
        if x==y:
            return "E"


In [ ]:
print(ifConfusion(2, 8))

E


In [ ]:
print(3**4)

81


In [ ]:
str = 'ppy!'
fruit = 'a'.join(list(str))
print(fruit)

papaya!


In [ ]:
python = ['cool']
x = python in python
print(x)


False


In [ ]:
print("""
A
B
C
""" =="\nA\nB\nC\n")

True


In [ ]:
print(4**3)

64


In [ ]:
x = range(-1, 2)

In [ ]:
print(x)

range(-1, 2)


In [ ]:
for i in range(-1, 2):
    print(i)

-1
0
1


In [ ]:
l = [23, 344, 45, 6]
for i in range(len(l)-1, 0, -1):
    print(l[i])


6
45
344


In [ ]:
def bubblesort(lst):
    for passesLeft in range(len(lst)-1, 0, -1):
        for index in range(passesLeft):
            if lst[index] > lst[index+1]:
                lst[index], lst[index+1] = lst[index+1], lst[index]
    return lst 

print(bubblesort([66, 89, 49, 62, 9, 53, 59]))


[9, 49, 53, 59, 62, 66, 89]


Explanation
The bubble sort does exactly what you'd expect it to do. It sorts an input list by treating each element as a bubble that climbs up the list. Each bubble rises as long as it is greater than the list elements. If a list element is smaller or equal to a list element, the bubble stops to rise and the list element starts to bubble up.  The precise algorithm works as follows. The outer index variable "passesLeft" marks the index after which the right-hand list elements are already sorted. The inner index variable "index" goes from left to right until it reaches the index variable "passesLeft". On its way to the right, it switches two subsequent list elements if the first element is larger than the second element. Hence, after the first pass, the largest element in the list is on the right. As this right-most element is already sorted, we can reduce the size of the list to be sorted by one, i.e., decrement the variable border. Next, the second largest element will rise to the top, and the procedure repeats.

In [ ]:
def bubblesort(lst):
    for passesRight in range(0, len(lst)-1):
        for index in range(len(lst)-1, passesRight,-1):
            if lst[index] > lst[index-1]:
                lst[index], lst[index-1] = lst[index-1], lst[index]
    return lst 

print(bubblesort([66, 89, 49, 62, 9, 53, 59]))


[89, 66, 62, 59, 53, 49, 9]


In [ ]:
print(55/11)

5.0


In [ ]:
print(142+234+1)


377


In [ ]:
def ask_ok(prompt, repeat = 4, reminder = "Repeat!"):
    while true:
        ok = input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        repeat -= 1
        if repeat < 0:
            raise ValueError('invalid user response')
        print(reminder)



In [ ]:
 print(5+2==7)

True


In [ ]:
d = {0:'a', False: 'b', 1>2: 'c', bool([]): 'd'}
print(d[0])

d


In [ ]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
l1.append(l2)
print(l1)

[1, 2, 3, [4, 5, 6]]


In [ ]:
word ='galaxy'
print(word[:-2] + word[4:])
print(word[4:60])

galaxy
xy


In [ ]:
fs = [
    lambda x : x+1, 
    lambda x: x+x, 
    lambda x: x*x]
n = 0
for f in fs:
    n = f(n)
print(n)


4


In [ ]:
print(sum(range(0, 7)))

21


In [ ]:
import re
m = "Speedy Gonzalez"
r = re.findall('.', m)
result = len(r)==len(m)
print(result)

True


Explanation
The module re provides the function findall(regex, string) which takes two arguments. The first is a regular expression and the second one is the string against which we want to match the regex. The function findall() returns a list of all matches. In this puzzle our regular expression is '.' (one dot), which matches any single character. Since we use the function findall() we have as many matches as there are characters in the string. Therefore the length of the list with the results is equal to the length of the string and the output of the puzzle is True.

In [ ]:
xs = [[1, 2], [3, 4]]
ys = list(xs)
print(ys)
print(xs is ys)


[[1, 2], [3, 4]]
False


In [ ]:
print(range(-10, -100, -30)[1])

-40


In [ ]:
def is_even(n):
    if n & 1:
        return True
    else: 
        return False
is_even(6)

True

In [ ]:
l = [2, 3, 4]
l.append([[]])
#l.extend([])
print(len(l))

4


In [ ]:
print(sum(range(4, 10)))

39


In [ ]:
omga = {
    "Salmon":2260, 
    "Hering":1729,
    "Sardines": 1480, 
    "Flaxseeds":53400, 
    "Eggs": 400
}
y = sorted(omga, key = lambda x: omga[x])
print(y[-1])

Flaxseeds


In [ ]:
my_typle = 1, 1, 1==(1,1,1)
print(my_typle)

(1, 1, False)


In [ ]:
speeds = [
    ('car',180),
    ('bike',20.5), 
    ('boat', 55.3),
    ('ski', 31.8)
]
#fastest = max(speeds)
fastest = max(speeds, key = lambda x: x[1])
print(fastest[0])

car


Explanation
If we wanted to find the fastest vehicle with this code we would certainly fail, this is not what it does. Since we have a list of tuples, the max() function computes the max item only with the first entries of the tuples. From the given strings in the tuples 'ski' is the last word in the alphabet therefore max() returns 'ski'. If you want to find the max() from the second entries of the tuples, do it like this: max(speeds, key=lambda x: x[1]).

In [ ]:
print(20*45)

900


In [ ]:
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

salaries = np.array([alice, bob, tim])
print(salaries(a))
taxation = np.array([
    [0.2, 0.25, 0.22],
    [0.4, 0.5, 0.5],
    [0.1, 0.2, 0.1]])
max_income = np.max(salaries - taxation*salaries)
print(int(max_income))


81


In [ ]:
result = (lambda x, y : x&y)(5, 7)
print(bin(result))

0b101


In [ ]:
s  = 'terfinx'
s = ''.join(sorted(list(s)[3:7]) + list(s)[0:3])
print(s)

finxter


In [ ]:
text = ''' 
I'm not happy.
I don't want not dance.
I don't love ice cream.'''

parttern = "not | don't "
print(re.sub(parttern,'', text))

 
I'm happy.
I want dance.
I love ice cream.


Explanation
The re.sub(pattern, repl, string, count=0, flags=0) method returns a new string where all occurrences of the pattern in the old string are replaced by repl.  The puzzle shows how a negative sentiment can be quickly turned into a positive one by removing all occurrences of 'not ' and "don't ". (Notice the whitespaces.)

In [ ]:
x = np.array([[1, 3, 5],
              [1, 1, 1],
              [0,2,4]])
y = np.average(x, axis=1)
print(y[0])
print(y[1])
print(y[2])

3.0
1.0
2.0


In [ ]:
matrix = [
    (0, 1, 1),
    (2, 1, -1), 
    (-1, 0, 3)
]
d = [row[col] for col, row in enumerate(matrix)]
print(d)

[0, 1, 3]


In [ ]:
def encrypt(s):
    return ''.join(reversed(s))

def decrypt(s):
    return s[::-1]

cleartext = " Modibo SOW"
print(cleartext == decrypt(encrypt(cleartext)))

True


In [21]:
import re

fruits = [
    "apple",
    "banana", 
    "orange", 
    "kiwi"
]

lx = lambda x: re.match(".?.?a", x)!=None
result = list(map(lx, fruits))
print(result)
print(sum(result))

[True, True, True, False]
3


Explanation
The lambda expression lx checks if the regex .?.?a matches the string x and returns True or False depending on the result of the match. When there is a match, the function re.match() returns a match object and if we compare it to None we get True or False for match or no match. The regular expression matches if the input string starts with "a" or has an "a" at the second or third position. With the function map we map this lambda expression to the list of strings where .?.?a matches for "apple", "banana", "orange" and for "kiwi" it doesn't match. Therefore the result is a list of boolean values [True, True, True, False]. Finally we apply the function sum to the result list. Since True maps to 1 and False to 0 the sum is 3.

In [24]:
str = 'abc'
for _ in range(10):
    str = tuple(str)
print(len(str))
print(str)


3
('a', 'b', 'c')


In [28]:
import numpy as np 
W = np.array([0.7, 0.2, 0.1])
x = np.array([1131, 1142, 1140])
y = np.dot(W, x)
print(y)


1134.1


# Binary research 

In [30]:
def bsearch(l, value):
    lo, hi = 0, len(l)-1
    while lo <= hi:
        mid = (lo + hi)//2
        if l[mid] < value:
            lo = mid+1
        elif value < l[mid]:
            hi = mid -1
        else:
            return mid
    return -1

l = [0, 1, 2, 3, 4, 5, 6]
x = 6
print(bsearch(l, x))

6


In [31]:
print(51%3)

0


In [36]:
presidents=[
    "Modibo", 
    "Oumar", 
    "Amadou"
]

times_in_office = [4422,
                    2922,
                    2922]
x = list(zip(presidents, times_in_office))
print(x)
print(x[2][1])

[('Modibo', 4422), ('Oumar', 2922), ('Amadou', 2922)]
2922


In [35]:
pres = list(zip(*x))[0]
print(pres)
print(pres[-1])

('Modibo', 'Oumar', 'Amadou')
Amadou


In [37]:
a = np.array([[1, 1],
              [1, 0]])
b = [[2, 0],[0, 2]]
c = np.matmul(a, b)
print(c[0, 1])

2


In [40]:
text  = ('What is the answer? '
            '42!' ' yes!')
print(text)

What is the answer? 42! yes!


In [42]:
words = ["computer", 'car', 'cat', 'cow', 'crow', 'window']
result = [w for w in words if re.match('.*w$', w)]
print(len(result))

3


In [43]:
print('''\
    A
    B
    C''')

    A
    B
    C


In [45]:
#Finaboni sequence with 8 first number
fibs = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21])
diff_fibs = np.diff(fibs)
print(diff_fibs[4])
print(diff_fibs.shape)

2
(8,)


Explanation
The numpy diff function calculates the difference between two subsequent values of a numpy array. Hence, an array with n elements results in a diff array with (n-1) elements.

# Matrix find

In [1]:
def matrixFind(matrix, value):
    m = len(matrix)
    if m == 0: 
        return False
    n = len(matrix[0])
    if n == 0:
        return False
    i = 0
    j = n - 1
    while i < m and j >=0:
        if matrix[i][j] == value:
            return True
        elif matrix[i][j] < value:
            i = i +1
        else:
            j - j-1
    return False

M= [[1, 4, 4, 4], [4, 6, 9, 10], [4, 9, 10, 13], [5, 12, 13, 14]]
print(matrixFind(M, 4))

True


In [2]:
print(5*3.8-1)

18.0


In [4]:
import re
target_folder = '''
                Student rankings:
                1. Bob
                2. Joe
                3.Charlie
                '''
parttern = r'(\d).*?(\w+)\n'
replacement = r'\2 ranks \1\n'

result = re.sub(parttern, replacement, target_folder)
print(result)


                Student rankings:
                Bob ranks 1
                Joe ranks 2
                Charlie ranks 3
                


Explanation
In this puzzle, we re-word the input text by taking the rank of each student to the end of the line. To do this, we capture the rank using the '(\d)' part of the string. We ignore the subsequent '.' character as well as the space. The student name is then captured by '(\w+)'. Note that we are able to match the regex for all three students because we also match the newline character '\n' at the end of the regex. This ensures that a running match ends with the current line, and each line is checked for a possible match.

In [10]:
import numpy as np

sat_scores = np.array([1440, 1256, 1543, 1043, 989, 1412, 1343])
students = np.array(["John", "Bob", "Alice", "Joe", "Jane", "Frank", "Carl"])
print(np.argsort(sat_scores))
print(students[np.argsort(sat_scores)])
top_3 = students[np.argsort(sat_scores)][:-4:-1]
print(top_3[:3:1])

[4 3 1 6 5 0 2]
['Jane' 'Joe' 'Bob' 'Carl' 'Frank' 'John' 'Alice']
['Alice' 'John' 'Frank']


In [13]:
s = "modibo sow 123k pixels".split()
l = list(map(lambda x: x if len(x)<3 else "duck", s))
print(l.count('duck'))

4


In [14]:
def add(a=0, b =1):
    return a+b

print(add(add()))

2


In [21]:
l = [("Perry", "music", 105), 
("Bierber", "music", 103),
("Obama", "politics", 96), 
("Swift", "music", 85)]
polit_starts = filter(lambda x: x[1]=="politics", l)
print(list(polit_starts)[0][0])


Obama


In [26]:
graph = [1, 1, 0, 0, 0]
for index, edges in enumerate(graph):
    print(index)
    print(edges)


0
1
1
1
2
0
3
0
4
0
